// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	OpenId   string
	Nickname string `json:"username"`
	Gender   string `json:"password"`
	Avar     string `json:"avar"`
	City     string `json:"city"`
}

type LoginReply struct {
	Status string `json:"status"`
	Mes    string `json:"mes"`
}
