// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package user -source $GOFILE

package user

import (
	"context"

	"rpc/proto"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	UserResponse = proto.UserResponse
	IdRequest    = proto.IdRequest

	User interface {
		GetUser(ctx context.Context, in *IdRequest) (*UserResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdRequest) (*UserResponse, error) {
	client := proto.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in)
}
